### ISSUE TITLE
Use Markdown for documents.

### ISSUE THREAD

**Issue by michael-oneill** [w3c/web-advertising#10]
It would be a lot easier for other contributors to edit MD documents, and we can take advantage of Github's built-in editing etc. 
In the call I offered to convert the UseCasesofOnlineAdvertising.html, file to Markdown. Unless Wendell is already planning to do it?

**Comment by michael-oneill** [comment]
UseCasesofOnlineAdvertising.md now exists

**Comment by wseltzer** [comment]
Thanks @michael-oneill! Sounds as though we can close this issue.
