### ISSUE TITLE
Explain the working and inputs behind the 95% FLoC claim

### ISSUE THREAD

**Issue by jwrosewell** [w3c/web-advertising#109]
![image](https://user-images.githubusercontent.com/1679482/109129099-2a8a7600-7748-11eb-900f-06ea2e374e84.png)

During the Improving Web Advertising Business Group meeting of 23rd February 2021 a representative from Google presented a diagram similar to the one shown above and addressed any confusion over the inclusion of remarketing in the 95% calculation.

However we were not in the time available on 23rd able to understand the working behind the 95% figure. Others via their own experiments are unable to work out how such a high figure could be achieved based on the limited information presented. 

Given the importance of this particular figure to the current perception of cohort based marketing across the digital marketing industry, and the unfortunate media attention it drew in January 2021, I would appreciate a clear explanation of the calculation. 

This explanation will then enable those that are asked by their customers to explain the approach they will be using to provide a cohort based post 3PC solution that is 95% as effective as the one they provide today to present an answer. Such customers might reasonably ask for a reduction in fees proportional to the reduction in effectiveness, or might seek alternative solutions to spend their money on which are not so impaired.

**Comment by mattprohaska** [comment]
From what we've seen, GOOG's methodology is reliant on all spend happening in their O&O inventory and with their buy-side/sell-side stack, so seems reasonable to assume it would be at least 95%...we're looking into developing research to show impact of not using FLoC, working with 1-100 companies, if anyone's interested in participating/providing thoughts. Thanks

**Comment by jwrosewell** [comment]
It appears as if there is no appetite from anyone involved in the 95% claim to answer this question and provide the workings for inspection. I'll therefore close it.
