### ISSUE TITLE
Active field trial groups- enterprise chrome 

### ISSUE THREAD

**Issue by khaderm786** [w3c/web-advertising#131]
Hello all,

We are experiencing significant performance degradation when we are uploading attachments via our Web App due to Active Field Trial Groups settings set by Google for certain users in our corporate using Enterprise Chrome 

We would like to open the support request and have the support team work with my team and IT staff to address the issue 

I am happy to expand more on the issue over the phone or a chat 

I can be reached at Khader.mohammed@everestre.com 

Thanks for all the support,
Khader

**Comment by wseltzer** [comment]
It sounds as though you want to report an issue or bug to the Chrome team, not here. Take a look at https://developer.chrome.com/
