### ISSUE TITLE
Duplicate Definition of "Impression"

### ISSUE THREAD

**Issue by bradhowes** [w3c/web-advertising#30]
There are two uses of the word "impression", one for a publisher and one for an advertiser (emphasis mine):

> Since we're discussing the web ads ecosystem, the publisher web pages we care about will generally have ads on them. That means you can think of publishers as creating web pages containing empty rectangles — rectangles which they want to sell to advertisers. Since publishers sell empty rectangles, they are referred to as the sell side or the supply side of the market. The empty rectangles themselves are sometimes referred to as ad slots or **impressions**, or as inventory when thinking of them as something being sold.
>...
> Since advertisers buy rectangle-shaped real estate to put their ads in, they are referred to as the buy side or the demand side of the market. When a specific ad creative appears on a user's load of a publisher web page, the event is called an **impression**.

Is this intentional? I was not aware of an empty ad space being referred to as an impression as well.

**Comment by michaelkleber** [comment]
Hi Brad,

Yup it's true, the term "impression" is somewhat ambiguous, and we've had it used in our group's conversations to mean both things.  Publishers talk about "unfilled impressions", for example, where no ad is shown.  And we've had people talk about impressions going into an RTB auction, before there is even a buyer, much less anything returned to the browser.

I'm sure someone speaking carefully could avoid these uses, and reserve the term "impression" for the advertiser's definition.  But seems like both happen in casual conversation.
