### ISSUE TITLE
Setup session for Internet Advertising Bureau (IAB) Tech Lab (TL) to present on Partnership for Responsible Addressable Media (PRAM)

### ISSUE THREAD

**Issue by jwrosewell** [w3c/web-advertising#85]
As part of wider W3C stakeholder engagement capture more information on the needs of brands and their technical requirements.

This is a mirror of the issue raised under [First Party Sets](https://github.com/privacycg/first-party-sets/issues/24).

**Comment by wseltzer** [comment]
Done: https://www.w3.org/2021/05/04-web-adv-minutes.html#t02
